### ISSUE TITLE
Preiselbeeren für Karin ?

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#10]
mytime.de
1,99 Euro
Spreewaldhof Wild-Preiselbeeren (400 g)

**Comment by speednic** [comment]
EDEKA (Gut & Güsntig) 1,37 Euro ... nur 5 vorhanden ... https://ssl.ecola.com/?p=artdetails&from_page=search&Artikel=100001045

**Comment by Holgerreetz** [comment]
http://www.mytime.de/Konserven/Obst/Preiselbeeren/Kuestengold_Wild-Preiselbeeren_4502040628.html?product_id=137b83c1b98f42aa94f2f86f3f55f51f&category_id=210006956
1,49 €

**Comment by speednic** [comment]
die küstengold haben aber nur 220g füllmenge ... die spreewaldhof 400g !!!

**Comment by speednic** [comment]
die nehme ich bei Edeka (mit den Artischoken) ... würd da auch mehr nehmen als die 12 für karin oder ?

**Comment by Holgerreetz** [comment]
kannst ja 6 zum probieren  mehr nehmen  

-------Originalmeldung-------

Von: speednic

Datum: 15.01.2015 15:23:44

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] Preiselbeeren für Karin ? (#10)

die nehme ich bei Edeka (mit den Artischoken) ... würd da auch mehr nehmen
als die 12 für karin oder ?

**Comment by speednic** [comment]
ok, im sheet stehn 20 :)

**Comment by Holgerreetz** [comment]
soll so bleiben. 

-------Originalmeldung-------

Von: speednic

Datum: 15.01.2015 15:39:57

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] Preiselbeeren für Karin ? (#10)

ok, im sheet stehn 20 :)

**Comment by speednic** [comment]
BESTELLT bei EDEKA ... 24x 1,39 EUR ... weil da haben mich selber schon ein paar gefragt ..
