### ISSUE TITLE
www.lebensmittel.de - wichtige Vergleichsseite !!!

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#12]
auch sehr gute preise - z.B. fisch http://www.lebensmittel.de/?p=artdetails&from_page=search&Artikel=100000211 um nur 0,85 (jeden Tag 200g) !!!!

**Comment by speednic** [comment]
https://ssl.ecola.com/?p=infoseiten/zahlungsangebote

a. Lieferkosten und Lieferzeit
Liefergebiete   bundesweit
unter 40 €    4,90 €
ab 40 €   0,00 €

**Comment by Holgerreetz** [comment]
Na dann mal los mit bestellen,  trage bitte die mengen und preise in die tabelle ein
