### ISSUE TITLE
chips ?? sind hier in PY teuer ...

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#13]
Jeden Tag Chips Paprika 
1 x 200 g / Beutel
0,40 € / 100g
Lager
0,79 € \*

**Comment by speednic** [comment]
Hab 20x Saltzstangen/Brezel bestellt, 300g für 1,35 (kosten normal 1,99) weil das geht mit dem Senf-Eimern mit als Versand :)

**Comment by speednic** [comment]
jeden tag chips 250g in AT um 1 Euro (ggf. als Paketfüller für Bierdosen ???

**Comment by Holgerreetz** [comment]
Ja,ist eine gute idee

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 25.01.2015  17:17  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Betreff: Re: [pyimport] chips ?? sind hier in PY teuer ... (#13)

jeden tag chips 250g in AT um 1 Euro (ggf. als Paketfüller für Bierdosen ???

---

**Comment by speednic** [comment]
also via AT gibts flips, chips, brezel, usw. :dancers: als paketfüller
