### ISSUE TITLE
Jägermeister 0,7

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#14]
10,99 Euro bei LM.de https://ssl.ecola.com/?p=artdetails&from_page=search&Artikel=100002089 

müsste man eigentlich billiger bekommen ...

**Comment by speednic** [comment]
bei LM.de brauch ich unbedingt PayPal :-1:

**Comment by speednic** [comment]
REWE in Wiesbaden hat Lieferservice ... 10,89 EUR ... frage ist nur wie liefern die aus - offen oder in schachteln verpackt ?? weil sollte ned unbedingt auffallen das da was zum saufen drinnen ist ...

**Comment by Holgerreetz** [comment]
die werden schon verpakt mache dir da keine sorgen 

habe da 24 fl aufgeschrieben 

-------Originalmeldung-------

Von: speednic

Datum: 01/14/15 23:42:20

An: SPEEDNIC-SRL/pyimport

Betreff: Re: [pyimport] Jägermeister 0,7 (#14)

REWE in Wiesbaden hat Lieferservice ... 10,89 EUR ... frage ist nur wie
liefern die aus - offen oder in schachteln verpackt ?? weil sollte ned
unbedingt auffallen das da was zum saufen drinnen ist ...

**Comment by speednic** [comment]
Für Karin brauchen wir 9 flaschen ... würde nur 18 bestellen, weil jägermeister kommt immer wieder her und so billig ist er auch nicht ... was verlangte Casa Rica für die 0,7er ??

**Comment by speednic** [comment]
habs schon ... 95.000 gs :dart:

**Comment by Holgerreetz** [comment]
95 000 guarani 

-------Originalmeldung-------

Von: speednic

Datum: 15.01.2015 13:04:05

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] Jägermeister 0,7 (#14)

Für Karin brauchen wir 9 flaschen ... würde nur 18 bestellen, weil
jägermeister kommt immer wieder her und so billig ist er auch nicht ... was
verlangte Casa Rica für die 0,7er ??

**Comment by speednic** [comment]
BESTELLT via EBay ... 18 stk. 193,50 + 4,95 versand
