### ISSUE TITLE
Nutella 450g für Karin

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#16]
3,29 EUR (450g) ... http://www.ebay.de/itm/NUTELLA-FERRERO-BROTAUFSTRICH-NUSSNOUGATCREME-450g-7-31EUR-1kg-/130935266241?pt=LH_DefaultDomain_77&hash=item1e7c599bc1

im Angebot bei Real & Co. meistens 2,69 EUR ...

**Comment by speednic** [comment]
2,59 EUR im ebay ... http://cgi.ebay.de/ws/eBayISAPI.dll?ViewItem&item=111145322862 ... leider nur 2 stk, habe aber angefragt auf MHD und 50 Stk.

**Comment by speednic** [comment]
3,14 EUR im ebay ... http://www.ebay.de/itm/7-85-1kg-Ferrero-Nutella-450g-Glas-Brotaufstrich-/310920663806

**Comment by speednic** [comment]
2,59 EUR ... edeka .. http://www.edeka-lieferservice.de/produkte/nahrungsmittel/brotaufstrich/352/ferrero-nutella-450g

**Comment by speednic** [comment]
1,50 EUR ... wahnsinn ... http://pageflip.v-markt.de/schwaben_oberbayern/0801_VMALL.html#1/z

**Comment by speednic** [comment]
2,59 bei worldofsweets... 10% rabatt und 50g gratis :)

**Comment by Holgerreetz** [comment]
die nehmen wir  

-------Originalmeldung-------

Von: speednic

Datum: 01/14/15 22:42:38

An: SPEEDNIC-SRL/pyimport

Betreff: Re: [pyimport] Nutella 450g für Karin (#16)

2,59 bei worldofsweets... 10% rabatt und 50g gratis :)

**Comment by speednic** [comment]
gekauft 45 Stk. um 2,59 (rabatt rechne ich nicht mit)
