### ISSUE TITLE
Erdnüsse / Flips

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#17]
brauchen auch noch Erdnüsse, das wollen die Leute auch ...

0,79 von Jeden Tag 200g (mytime.de)
0,69 bei Aldi im Angebot 200g
0,99 Euro von Xox Erdnussflips (200 g) bei mytime.de

Menge würd ich so 50 herum sagen ...

**Comment by speednic** [comment]
mein bruder hat erdnüsse organisiert ... 500g dosen ... 

sollten wir da noch mehr nehmen ?? oder eher weglassen ??

**Comment by Holgerreetz** [comment]
Sollten 20 sein

Saludos

Holger Reetz

Atlantida  Uruguay

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: speednic <notifications@github.com> </div><div>Datum:22.01.2015  22:00  (GMT-04:00) </div><div>An: SPEEDNIC-SRL/pyimport <pyimport@noreply.github.com> </div><div>Betreff: Re: [pyimport] Erdnüsse / Flips (#17) </div><div>
</div>

mein bruder hat erdnüsse organisiert ... 500g dosen ...

sollten wir da noch mehr nehmen ?? oder eher weglassen ??

---

**Comment by speednic** [comment]
leider nicht mehr im anbot .. somit aktuell nur 10 stk. via AT
