### ISSUE TITLE
www.edeka-lieferservice.de - auch nicht schlecht ...

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#18]
durch LIMBURG draufgekommen .... ;) jetzt bräuchten wir nur noch wen der dort wohnt _lool_

**Comment by speednic** [comment]
Edeka gibts in Heidesheim, habe denen eine Anfrage geschickt per EMail ob die uns ggf. was liefern würden ... aktuelle Angebote : 

3,49 EUR Haribo 1kg
1,19 EUR Prinzenrolle 400g
1,49 EUR Erasco Eintöpfe 800g
1,11 EUR Hawesta Heringfilet 200g

**Comment by speednic** [comment]
bis dato keine antwort - somit thread geschlossen ...

**Comment by Holgerreetz** [comment]
War schonalles richtig so

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 16.01.2015  23:39  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Betreff: Re: [pyimport] www.edeka-lieferservice.de - auch nicht schlecht ... (#18)

bis dato keine antwort - somit thread geschlossen ...

---
