### ISSUE TITLE
KNAX Gurken ??

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#19]
1,49 EUR ... 360g abtropf, wie die aktuellen gläser 720g .... http://www.edeka-lieferservice.de/produkte/nahrungsmittel/konserven/sauerkonserven/144/hengstenberg-knax-gewuerzgurken?c=113

**Comment by speednic** [comment]
0,99 EUR ... alternative wen keiner die um 0,95 hohlt ... https://www.edeka-lebensmittel.de/lebensmittel/gut-guenstig-gewuerzgurken-auslese-670g/a-1349497938/

**Comment by Holgerreetz** [comment]
Die nehmem wir

Saludos

Holger Reetz

Atlantida  Uruguay

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: speednic <notifications@github.com> </div><div>Datum:16.01.2015  12:17  (GMT-04:00) </div><div>An: SPEEDNIC-SRL/pyimport <pyimport@noreply.github.com> </div><div>Betreff: Re: [pyimport] KNAX Gurken ?? (#19) </div><div>
</div>

0,99 EUR ... alternative wen keiner die um 0,95 hohlt ... https://www.edeka-lebensmittel.de/lebensmittel/gut-guenstig-gewuerzgurken-auslese-670g/a-1349497938/

---

**Comment by speednic** [comment]
also die ersten beiden Küstengold wären interessant, wobei vom Topf eher wenige ... kühne könnte man sich überlegen (Kühne aktuell draussen 0,99), hengstenberg zu teuer ... 

Küstengold Gewürzgurken Auslese (360g/670g)   0,99 Euro (puesto ca. 11000)
Küstengold Gurkentopf (850g/1550g) 1,49 Euro (puesto ca. 20000)
Kühne Gewürzgurken Auslese (360g/670g)    1,39 Euro (puesto ca. 13500)
Hengstenberg KNAX Gewürzgurken (360g/670g) 1,69 Euro (puesto über 15000 zu teuer)

**Comment by Holgerreetz** [comment]
nehmen wir die kühne auslese  

-------Originalmeldung-------

Von: speednic

Datum: 01/19/15 13:00:00

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] KNAX Gurken ?? (#19)

also die ersten beiden Küstengold wären interessant, wobei vom Topf eher
wenige ... kühne könnte man sich überlegen (Kühne aktuell draussen 0,99),
hengstenberg zu teuer ... 

Küstengold Gewürzgurken Auslese (360g/670g) 0,99 Euro (puesto ca. 11000)

Küstengold Gurkentopf (850g/1550g) 1,49 Euro (puesto ca. 20000)

Kühne Gewürzgurken Auslese (360g/670g) 1,39 Euro (puesto ca. 13500)

Hengstenberg KNAX Gewürzgurken (360g/670g) 1,69 Euro (puesto über 15000 zu
teuer)

**Comment by speednic** [comment]
kühne zu teuer bis sie hier sind ... küstengold bestellt, gurkentopf weggelassen weil vom volumen her zu gross und kommen dann auf fast 25mil ...

BESTELLT --> siehe Mytime Thread
