### ISSUE TITLE
EK ebay - Bautzner Senf

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#2]
Hallo, ich bin an Ihrem Bautzner Senf interessiert und würde mind. 12 Eimer benötigen. Da der Versand (via deutsche Lieferadresse) aber per Container ins Ausland verfrachtet wird richtet sich meine Frage an das MHD, das in der Beschreibung lediglich mit 03/2015 angegeben ist, und somit für die Seefracht leider zu kurz ist. Der Versand würde zeitnah erfolgen, Ankunft dann 04/2015, also würde ich mind. ein MHD von mind. 07+/2015, besser frischer benötigen ? Haben Sie hier ggf. aktuell längere MHD auf Lager ? Danke Alex

**Comment by speednic** [comment]
user: traderjette
1,99 EURO + Versand

Hallo, Im Moment habe ich Juni und Juli als MHD.
Wenn der Versand noch bis Donnerstag Zeit hätte könnte ich sogar ein längereres MHD ermöglichen. Da ich am Donnerstag wieder neue Ware bekomme.
Den Kauf können wir dennoch schon abwickeln wenn Sie möchten.Ingo

**Comment by speednic** [comment]
Hallo Ingo, danke für die prompte Antwort. Ich habe gerade nochmal Rücksprache mit einem Partner gehalten und wir würden gerne 24x 1L-Eimer haben wollen. Desto länger das MHD desto lieber ist uns dieses, damit wir einen gewissen MHD-Verlust durch Transport-/Importverzögerung ausschliessen können. Haben Sie vom "scharfen" auch den 1L-Eimer oder nur die kleinen 200ml ? Weil wenn würden wir auch ein paar 1L-scharf nehmen wollen. Vom Versand her haben wir auf jedenfall bis Anfang Februar Zeit bis die Ware beim Container sein muss, also von da her kein Problem. Nach Durchsicht Ihrer Artikel werden wir wahrscheinlich auch noch andere Produkte von Ihnen kaufen. Nähere Details würde ich Ihnen dann durchsenden. Danke Alex

**Comment by speednic** [comment]
GEKAUFT vorab 12 Stk. + Versand

**Comment by speednic** [comment]
Hallo, Vom Scharfen habe ich nur die 200ml Becher im Sortiment.MFG Ingo

nehmen wir vom 200ml scharfen auch was ?? ist halt nur teurer (ca. 3,30 aufs KG)

**Comment by speednic** [comment]
event. interessant ? http://www.ebay.de/itm/Born-Knoblauchsenf-200ml-/261178427373?pt=Nahrungsmittel_Spezialit%C3%A4ten&hash=item3ccf7287ed

**Comment by speednic** [comment]
1,29 euro (0,65) für 2 becher 200ml bei dem typen, lebensmittel.de verlangt 0,69 ... also würd ich bei dem mitbestellen so scharfe weil der versand verändert sich nicht viel dadurch ... frage wieviel ? 12 oder mehr ? oder eher tuben ?

**Comment by Holgerreetz** [comment]
eher tuben, laenger haltbar und kleiner im kühlschrank

**Comment by Holgerreetz** [comment]
karin will 50 x mittelscharfen und 24 süssen senf

**Comment by speednic** [comment]
GEkAUFT via Ebay ... 225,22 inkl. 30 Euroversand
