### ISSUE TITLE
LIDL Produkte ??

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#20]
11,99 EUR .... http://www.ebay.de/itm/Lidl-Prinzessbohnen-10-x-800-g-Konserve-MHD-2017-Fertiggericht-1-49-kg-/361158753240?pt=LH_DefaultDomain_77&hash=item5416bd3bd8

11,99 EUR ... http://www.ebay.de/itm/Lidl-Erbsen-mit-Mohrchen-10-x-800-g-Konserve-MHD-2017-Fertiggericht-1-49-kg-/311224506954?pt=Gro%C3%9Fhandelsposten&hash=item48766d1a4a

**Comment by speednic** [comment]
0,99 EUR ... http://www.lidl.de/de/harvin-sauerkirschen/p187916

**Comment by Holgerreetz** [comment]
Sauerkirschen und Bohnen  ja ,Erbsen und Wurzeln  nein

**Comment by speednic** [comment]
BESTELLT 
59,95 EUR inkl. Versand ... 50x Prinzessbohnen 800g MHD 2017

**Comment by speednic** [comment]
Sehr geehrte Kundin, sehr geehrter Kunde,

die Sendung "Ebay Alex Bohnen" mit der Sendungsnummer 276437797322 befindet sich 
derzeit in folgendem Status: Die Sendung wurde beschädigt und wird zur 
Nachverpackung in das Paketzentrum zurückgesandt.

von 3 paketen sind 2 mit beschädigt gekennzeichnet _grml_

**Comment by Holgerreetz** [comment]
Alles deppen nicht mal richtig packen können die

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 17.01.2015  20:46  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Cc: Holgerreetz reetz_4@hotmail.com
Betreff: Re: [pyimport] LIDL Produkte ?? (#20)

Sehr geehrte Kundin, sehr geehrter Kunde,

die Sendung "Ebay Alex Bohnen" mit der Sendungsnummer 276437797322 befindet sich
derzeit in folgendem Status: Die Sendung wurde beschädigt und wird zur
Nachverpackung in das Paketzentrum zurückgesandt.

von 3 paketen sind 2 mit beschädigt gekennzeichnet _grml_

---

**Comment by speednic** [comment]
noch immer nix weiter bei dem ...

**Comment by speednic** [comment]
sind zum glück jetzt endlich angekommen ... will gar ned wissen wie _ggg_
