### ISSUE TITLE
Teebaumöl 

### ISSUE THREAD

**Issue by Holgerreetz** [SPEEDNIC-SRL/pyimport#21]
http://www.amazon.de/Teebaum%C3%B6l-100%25-naturreines-%C3%A4therisches-10ml/dp/B008DV1DT0/ref=sr_1_2?ie=UTF8&qid=1421152597&sr=8-2&keywords=Teebaum%C3%B6l

nicht mehr wie 20 bestellen

**Comment by speednic** [comment]
BESTELLT

20x 2,19 EUR = 43,80 + 12,51 Versand ... total 56,31 EUR
lieferung 6-9 Werktage

**Comment by speednic** [comment]
Voraussichtlicher Liefertermin: Freitag, 23. Januar 2015 - Donnerstag, 29. Januar 2015
