### ISSUE TITLE
Puddingpulver

### ISSUE THREAD

**Issue by Holgerreetz** [SPEEDNIC-SRL/pyimport#24]
50 X  
  http://www.mytime.de/product.php?product_id=cc658c30c82e57b55053b99a91b712c5&search_query=ruf+puddingpulver

20 X
http://www.mytime.de/product.php?product_id=cc68271ea4faad3a8e7ea65327c2ec74

50 X
http://www.mytime.de/Fertiggerichte/Dessert_und_suesse_Speisen/Puddingpulver/Vanillepuddingpulver/Ruf_Puddingpulver_Vanille_4502111234.html?product_id=cc5e88f6ca10324208c5c398bdc7db99&category_id=210006814

50 X 
http://www.mytime.de/Fertiggerichte/Dessert_und_suesse_Speisen/Puddingpulver/Schokoladenpuddingpulver/Ruf_Puddingpulver_Schokolade_4502111247.html?product_id=cc628127622879d3bf8c89d01269c2b9&category_id=210006813

30 X 

http://www.mytime.de/Fertiggerichte/Dessert_und_suesse_Speisen/Dessertsaucen/Ruf_Sossenpulver_Vanille_ohne_Kochen_4502111264.html?product_id=cc68825427d73a808965e27585dc36c8&category_id=210002828

**Comment by Holgerreetz** [comment]
http://www.mytime.de/search_result.php?search_query_keyword=cremepulver+ruf

je 10 
ausnahme   Erdbeer und mousse au chocolate

**Comment by speednic** [comment]
BESTELLT --> siehe Mytime Thread
