### ISSUE TITLE
süsser senf 

### ISSUE THREAD

**Issue by Holgerreetz** [SPEEDNIC-SRL/pyimport#27]
https://www.allyouneed.com/cat/?artid=22847&ia-pkpmtrack=100-9353735313236323131303-111-261-101&campaign=psm/ladenzeile/22847

sind zwar nur 200 gr gläser  dafür nur 1,09 €

**Comment by speednic** [comment]
link geht nicht ... was für senf ist das ?

**Comment by Holgerreetz** [comment]
https://www.allyouneed
com/cat/Kochen+%26+Backen/H%C3%A4ndlmaier%27s+Altbayerischer+Senf%2C+200%26nb
p%3Bml?catid=9173&artid=9693&mode=shop

wenn nicht öffnet, dann auf Hauptseite  und süssen senf suchen 

Hädelmeier 200 gr  1,19 €

-------Originalmeldung-------

Von: speednic

Datum: 15.01.2015 20:05:11

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] süsser senf (#27)

link geht nicht ... was für senf ist das ?

**Comment by speednic** [comment]
also senf bekommen wir über Amazon auch zu günstigen preisen, ein paar sind bei mytime um 10c billiger aber auch teurer .... also in AT kostet süsser senf (bei uns heist der KREMSER Senf) 1,39 Euro wie eigentlich alle 200ml tuben im supermarkt ...

**Comment by speednic** [comment]
der Händlmaier 200ml süss kostet auch 1,39 bei Amazon & Co.

**Comment by speednic** [comment]
SENF wurde bestellt bei Amazon ...

15x Händlmaier SENF Süss     a 1,39 EUR
15x Händlmaier Senf Mittelsch    a 1,037 EUR
24x Thomy Delikatess-Senf   a 1,09 EUR
24x Kühne Senf Mittelscharf   a 0,99 EUR

gesamt    86,33 EUR

der restl. senf SÜSS kommt dann aus AT über meinen Bruder (karin will nämlich 24 süs / 50 Mittels)
