### ISSUE TITLE
Pumpernickl

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#28]
1,39 EUR ... 250g ... http://www.ebay.de/itm/5-56EUR-1kg-MESTEMACHER-GOURMET-PUMPERNICKEL-WESTFALISCH-250g-/131118363236?pt=LH_DefaultDomain_77&hash=item1e87437264

**Comment by Holgerreetz** [comment]
nein, ist zu teuer

sollte auch gemischtes schwarzbrot sein   kümmere ich mich drum  

-------Originalmeldung-------

Von: speednic

Datum: 14.01.2015 09:36:53

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Pumpernickl (#28)

1,39 EUR ... 250g ... http://www.ebay
de/itm/5-56EUR-1kg-MESTEMACHER-GOURMET-PUMPERNICKEL-WESTFALISCH-250g-/1311183
3236?pt=LH_DefaultDomain_77&hash=item1e87437264

**Comment by Holgerreetz** [comment]
http://www.ebay
de/itm/3-98EUR-1kg-MESTEMACHER-BROTKORBCHEN-500G-EINZELN-VERPACKTE-VOLLKORNBR
TE-/131118363259?pt=LH_DefaultDomain_77&hash=item1e8743727b

500 gr   1,99 und gemischt 

-------Originalmeldung-------

Von: speednic

Datum: 14.01.2015 09:36:53

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Pumpernickl (#28)

1,39 EUR ... 250g ... http://www.ebay
de/itm/5-56EUR-1kg-MESTEMACHER-GOURMET-PUMPERNICKEL-WESTFALISCH-250g-/1311183
3236?pt=LH_DefaultDomain_77&hash=item1e87437264

**Comment by Holgerreetz** [comment]
http://www.mytime.de/product
php?product_id=9e781ddc1cfcadb7772281a8b768c761&search_query=pumpernickel

hier nur 1,29 für 500gr,   die nehmen wir    50 St 

http://www.ebay
de/itm/3-98EUR-1kg-MESTEMACHER-BROTKORBCHEN-500G-EINZELN-VERPACKTE-VOLLKORNBR
TE-/131118363259?pt=LH_DefaultDomain_77&hash=item1e8743727b

500 gr   1,99 und gemischt 

-------Originalmeldung-------

Von: speednic

Datum: 14.01.2015 09:36:53

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Pumpernickl (#28)

1,39 EUR ... 250g ... http://www.ebay
de/itm/5-56EUR-1kg-MESTEMACHER-GOURMET-PUMPERNICKEL-WESTFALISCH-250g-/1311183
3236?pt=LH_DefaultDomain_77&hash=item1e87437264

**Comment by speednic** [comment]
BESTELLT --> siehe Mytime Thread
