### ISSUE TITLE
Haribo

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#29]
1,69 EUR .. 360g ... http://www.ebay.de/itm/4-69EUR-1kg-HARIBO-GOLDBAREN-360G-MAXIPACK-FRUCHTGUMMI-WEINGUMMI-/131106330100?pt=LH_DefaultDomain_77&hash=item1e868bd5f4

**Comment by speednic** [comment]
1,89 EUR ... 500g ... http://www.ebay.de/itm/RED-BAND-FRUCHTGUMMI-SCHNULLER-500g-BEUTEL-3-76EUR-1kg-/130546709783?pt=LH_DefaultDomain_77&hash=item1e6530b517

**Comment by Holgerreetz** [comment]
sollten bei den 200 gr packungen bleiben 

-------Originalmeldung-------

Von: speednic

Datum: 14.01.2015 09:42:27

An: SPEEDNIC-SRL/pyimport

Betreff: Re: [pyimport] Haribo (#29)

1,89 EUR ... 500g ... http://www.ebay
de/itm/RED-BAND-FRUCHTGUMMI-SCHNULLER-500g-BEUTEL-3-76EUR-1kg-/130546709783?p
=LH_DefaultDomain_77&hash=item1e6530b517

**Comment by speednic** [comment]
für die Masse sicherlich, aber gibt auch Leute die gern grössere Pakete kaufen btw. RedBand ist sehr gut und günstig im Verhältniss.

**Comment by speednic** [comment]
www.worldofsweets.de

267 EUR
    5 EUR Versand
-10% Rabattcode :+1: 

20x Haribo Süsse Mäuse
10x Haribo Tierpuzzle
10x Haribo Waldgeister
10x Haribo Happy Cola Lemon Fresh
10x Haribo Pandas
20x Haribo Phantasia
10x Haribo Bärenschule
20x Haribo Quaxi Fröschli
20x Haribo Fruity Cocktail
10x Haribo Kinder Schnuller
10x Haribo Saure Schnuller
10x Haribo Wine Gums
10x Haribo Saure Pommes
20x Haribo Weinland
10x Haribo Goldbären
= 200 Stk.

20x Haribo Lakritz Parade
10x Haribo Black Cherries
10x Haribo Sali-Kritz
10x Haribo Katinchen
10x Haribo Piratos
10x Haribo Lakritz Schnecken
30x Haribo Color-Rado
= 100 Stk.

**Comment by speednic** [comment]
Gesamtbestellung bei SweetsofOnline

200x Haribo Gummi        0,89 Eur
100x Haribo ColorRado + Lakritz   0,89 EUR
  40x Haribo Chamallow       1,09 EUR
  30x Dextro-Energy (3er)    1,69 EUR
  12x Manner-Schnitten      0,49 EUR
  45x Nutella 450g + 50g    2,59 EUR

Summe : 483,73 EUR
Versand :    4,95 EUR
Rabatt :   -48,37 EUR
GESAMT : 440,31 EUR
