### ISSUE TITLE
10kg Tomatenketchung + Senf

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#3]
18,99 EUR ... http://www.ebay.at/itm/Kern-Gewurz-Sauce-Tomaten-Ketchup-10kg-Kanister-Gastronomie-/261433978650?pt=Nahrungsmittel_Spezialit%C3%A4ten&hash=item3cdeadef1a

ggf. andere Quelle ???

**Comment by speednic** [comment]
SENF 16,49 EUro + Versand ... http://www.ebay.de/itm/Bautzner-Senf-mittelscharf-10-kg-Eimer-/261178426951?pt=Nahrungsmittel_Spezialit%C3%A4ten&hash=item3ccf728647

**Comment by speednic** [comment]
senf 20,68 von kühne, lebensittel.de ... https://ssl.ecola.com/?p=artdetails&from_page=search&Artikel=100016371

**Comment by Holgerreetz** [comment]
brauchen noch curryketchup 10 kg eimer

**Comment by speednic** [comment]
14,99 euro ... http://www.ebay.de/itm/KUHNE-SENF-WURZIG-PIKANT-10KG-EIMER-1-50-1kg/130768434393?_trksid=p2047675.c100005.m1851&_trkparms=aid%3D222007%26algo%3DSIC.MBE%26ao%3D1%26asc%3D20140117130753%26meid%3D0ad12e893409449aa845f70a130f31d1%26pid%3D100005%26prg%3D20140117130753%26rk%3D1%26rkt%3D6%26sd%3D261178426951&rt=nc

**Comment by speednic** [comment]
BESTELLT EBAY
16,39 EUR inkl. Versand - 10kg Ketchup
25,85 EUR inkl. Versand - 10kg curry gewürzketchup

**Comment by speednic** [comment]
mist, hätte gerade ketchup um 13 EUR gefunden weil der kühne 10kg senf nicht mehr verfügbar ist, wäre um einiges billiger beim curry-ketchup gewesen, gut beim SENF halt weil der ist wo anders auch billiger, gibt aber nur 5kg kübel !!

**Comment by Holgerreetz** [comment]
dann nehmen wir halt 2 x 5 kg senf 

-------Originalmeldung-------

Von: speednic

Datum: 14.01.2015 08:47:18

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] 10kg Tomatenketchung + Senf (#3)

mist, hätte gerade ketchup um 13 EUR gefunden weil der kühne 10kg senf nicht
mehr verfügbar ist, wäre um einiges billiger beim curry-ketchup gewesen, gut
beim SENF halt weil der ist wo anders auch billiger, gibt aber nur 5kg kübel
!!

**Comment by speednic** [comment]
SENF BESTELLT --> siehe Mytime Thread
