### ISSUE TITLE
Gelierzucker 

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#30]
1,89 EUR ... 500g ... http://www.ebay.de/itm/Dr-Oetker-Extra-Gelierzucker-2-1-500g-3-78EUR-1kg-/131087590784?pt=LH_DefaultDomain_77&hash=item1e856de580

**Comment by Holgerreetz** [comment]
http://www.mytime.de/product
php?product_id=d51522a88e36a66c8b7ce84f60e6b239&search_query=gelierzucker

nur 0,79 cent  oder lieber das gelfix 

-------Originalmeldung-------

Von: speednic

Datum: 14.01.2015 09:44:05

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Gelierzucker (#30)

1,89 EUR ... 500g ... http://www.ebay
de/itm/Dr-Oetker-Extra-Gelierzucker-2-1-500g-3-78EUR-1kg-/131087590784?pt=LH_
efaultDomain_77&hash=item1e856de580

**Comment by speednic** [comment]
BESTELLT --> siehe Mytime Thread
