### ISSUE TITLE
Remoulade

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#31]
1,99 EUR ... 200ml ... http://www.ebay.de/itm/KUHNE-DANISCHE-ART-REMOULADE-200ML-9-95EUR-1l-/130849850651?pt=Nahrungsmittel_Spezialit%C3%A4ten&hash=item1e7742451b

**Comment by Holgerreetz** [comment]
Remoulade

http://www.mytime.de/product
php?product_id=a5155a636ea5aa85f23e3d6fa76a2cda&search_query=Remoulade  1,79
 hat nur 50 tage Haltbarkeit 

-------Originalmeldung-------

Von: speednic

Datum: 14.01.2015 09:48:46

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Remoulade (#31)

1,99 EUR ... 200ml ... http://www.ebay
de/itm/KUHNE-DANISCHE-ART-REMOULADE-200ML-9-95EUR-1l-/130849850651?pt=Nahrung
mittel_Spezialit%C3%A4ten&hash=item1e7742451b

**Comment by speednic** [comment]
BESTELLT --> siehe Mytime Thread
