### ISSUE TITLE
Artischocken

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#33]
2,19 EUR http://www.edeka24.de/Essen/Konserven/Gemuesekonserven/EDEKA+Artischocken+Herzen.html

**Comment by Holgerreetz** [comment]
die nehmen wir auch 

-------Originalmeldung-------

Von: speednic

Datum: 01/14/15 23:17:29

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Artischocken (#33)

2,19 EUR http://www.edeka24
de/Essen/Konserven/Gemuesekonserven/EDEKA+Artischocken+Herzen.html

**Comment by speednic** [comment]
nur die 24 für Karin ? Oder mehr ?

**Comment by Holgerreetz** [comment]
ja nur für karin 

-------Originalmeldung-------

Von: speednic

Datum: 15.01.2015 15:22:39

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] Artischocken (#33)

nur die 24 für Karin ? Oder mehr ?

**Comment by speednic** [comment]
weil du im sheet 30 angegeben hast

**Comment by Holgerreetz** [comment]
karin wollte 24  für uns 6  

-------Originalmeldung-------

Von: speednic

Datum: 15.01.2015 15:39:00

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] Artischocken (#33)

weil du im sheet 30 angegeben hast

**Comment by speednic** [comment]
BESTELLT bei EDEKA ... 24x 2,09 EUR
