### ISSUE TITLE
Kirschen

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#34]
1,99 EUR 680g (370 Abtropf) http://www.edeka24.de/Essen/Konserven/Obstkonserven/EDEKA+Schattenmorellen.html

**Comment by Holgerreetz** [comment]
zu teuer 

-------Originalmeldung-------

Von: speednic

Datum: 01/14/15 23:22:19

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Kirschen (#34)

1,99 EUR 680g (370 Abtropf) http://www.edeka24
de/Essen/Konserven/Obstkonserven/EDEKA+Schattenmorellen.html

**Comment by speednic** [comment]
BESTELLT --> siehe Mytime Thread
