### ISSUE TITLE
Peperoni mild 

### ISSUE THREAD

**Issue by Holgerreetz** [SPEEDNIC-SRL/pyimport#35]
http://www.edeka24.de/Hengstenberg+Milde+Peperoni.html?listtype=search&searchparam=peperoni%20mild&&order=

24 st  bestellen

**Comment by speednic** [comment]
finde ich etwas teuer ...

**Comment by Holgerreetz** [comment]
im nachhinein ich auch 

-------Originalmeldung-------

Von: speednic

Datum: 15.01.2015 11:06:14

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] Peperoni mild (#35)

finde ich etwas teuer ...

**Comment by speednic** [comment]
1,29 EUR ... 260g ... https://www.mytime.de/product.php?product_id=a36591ed709aa5a6af77f797ebad4128&search_query=Peperoni+mild

**Comment by speednic** [comment]
1,84 EUR .. externer anbieter ... 720ml ... http://www.amazon.de/Cuisine-Noblesse-Peperoni-mildem-Geschmack/dp/B00NIDD07G/ref=sr_1_17?s=grocery&ie=UTF8&qid=1421369059&sr=1-17&keywords=Peperoni+mild

**Comment by Holgerreetz** [comment]
Wir nehmen diese

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 15.01.2015  22:44  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Cc: Holgerreetz reetz_4@hotmail.com
Betreff: Re: [pyimport] Peperoni mild  (#35)

1,29 EUR ... 260g ... https://www.mytime.de/product.php?product_id=a36591ed709aa5a6af77f797ebad4128&search_query=Peperoni+mild

---

**Comment by speednic** [comment]
kack .. nur 12 verfügbar und dann gleich 12 euro versand ...

**Comment by Holgerreetz** [comment]
Nee dann nicht

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 15.01.2015  23:05  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Cc: Holgerreetz reetz_4@hotmail.com
Betreff: Re: [pyimport] Peperoni mild  (#35)

kack .. nur 12 verfügbar und dann gleich 12 euro versand ...

---

**Comment by Holgerreetz** [comment]
die sollten wir nehmen  

-------Originalmeldung-------

Von: speednic

Datum: 01/15/15 21:44:06

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] Peperoni mild (#35)

1,29 EUR ... 260g ... https://www.mytime.de/product
php?product_id=a36591ed709aa5a6af77f797ebad4128&search_query=Peperoni+mild

**Comment by speednic** [comment]
BESTELLT --> siehe Mytime Thread
