### ISSUE TITLE
Supermarkt DE - aktuell via Eddi

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#36]
Hier mal eine Auflistung der Sachen die ggf. Katja organisieren könnte ... menge könnte varieren btw. könnte man noch ein paar Sachen weglassen (z.B. Kategorie 2 und 3) ... bitte ggf. komentieren zur MENGE ...

ca. 700 Euro gesamt, btw. 310kg ;)

1.) WICHTIG
bei REAL     60 Stk. Hengstenberg KNAX Gewürzgurken (0,95 EUR)
bei REAL     25 Stk.Knorr Schlemmer-Saucen 250ml, divS. (0,69 EUR)
bei Edeka/Treff    100 Stk. Hawesta Heringsfilets 200g, divS. (1,11 EUR)
bei Edeka/Treff    100 Stk. Erasco Fertiggericht 800g, divS. (kein Reistopf) (1,49 EUR)
bei Treff3000    200 Stk. Maggi fix & frisch, div Sorten (0,49 EUR)
bei NETTO    100 Stk. Maggi Ravioli 800g, divS. (1,29 EUR)

2.) MITTEL
bei NETTO    50 Stk.    Maggi Guten Appetit Suppe, divS. (0,49 EUR)
bei Edeka/Treff    50 Stk. Ritter Sport Schoko, 100g, divS. (0,69 EUR)

3.) WENIGER
bei REAL    10 Stk. Funny-Frisch oder Ohio Chips 175g, (1,29 EUR)
bei EDEKA     5 Stk. Haribo Goldbären 1kg Packung (3,49 EUR)
bei Edeka-ECenter/Marktkauf  25 Stk. Kühne Senf mittelscharf 240ml Tube (+20% Inhalt) (0,99 EUR)
bei Edeka-ECenter/Marktkauf    20 Stk. Leimer Backerbsen 200g (+10% Inhalt) (0,88 EUR)

**Comment by Holgerreetz** [comment]
kann alles so wie es ist gekauft werden 

bei den fertiggerichten von maggi sollten wir nur 50 nehmen hast  ja noch ca
20  

-------Originalmeldung-------

Von: speednic

Datum: 01/16/15 07:53:50

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Katja Supermarkt (#36)

Hier mal eine Auflistung der Sachen die ggf. Katja organisieren könnte ...
menge könnte varieren btw. könnte man noch ein paar Sachen weglassen (z.B.
Kategorie 2 und 3) ... bitte ggf. komentieren zur MENGE ...

ca. 700 Euro gesamt, btw. 310kg ;)

1.) WICHTIG

bei REAL 60 Stk. Hengstenberg KNAX Gewürzgurken (0,95 EUR)

bei REAL 25 Stk.Knorr Schlemmer-Saucen 250ml, divS. (0,69 EUR)

bei Edeka/Treff 100 Stk. Hawesta Heringsfilets 200g, divS. (1,11 EUR)

bei Edeka/Treff 100 Stk. Erasco Fertiggericht 800g, divS. (kein Reistopf) (1
49 EUR)

bei Treff3000 200 Stk. Maggi fix & frisch, div Sorten (0,49 EUR)

bei NETTO 100 Stk. Maggi Ravioli 800g, divS. (1,29 EUR)

2.) MITTEL

bei NETTO 50 Stk. Maggi Guten Appetit Suppe, divS. (0,49 EUR)

bei Edeka/Treff 50 Stk. Ritter Sport Schoko, 100g, divS. (0,69 EUR)

3.) WENIGER

bei REAL 10 Stk. Funny-Frisch oder Ohio Chips 175g, (1,29 EUR)

bei EDEKA 5 Stk. Haribo Goldbären 1kg Packung (3,49 EUR)

bei Edeka-ECenter/Marktkauf 25 Stk. Kühne Senf mittelscharf 240ml Tube (+20%
Inhalt) (0,99 EUR)

bei Edeka-ECenter/Marktkauf 20 Stk. Leimer Backerbsen 200g (+10% Inhalt) (0
88 EUR)

—

Reply to this email directly or view it on GitHub.

kann alles so wie es ist gekauft werden 

bei den fertiggerichten von maggi sollten wir nur 50 nehmen hast  ja noch ca
20  

-------Originalmeldung-------

Von: speednic

Datum: 01/16/15 07:53:50

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Katja Supermarkt (#36)

Hier mal eine Auflistung der Sachen die ggf. Katja organisieren könnte ...
menge könnte varieren btw. könnte man noch ein paar Sachen weglassen (z.B.
Kategorie 2 und 3) ... bitte ggf. komentieren zur MENGE ...

ca. 700 Euro gesamt, btw. 310kg ;)

1.) WICHTIG

bei REAL 60 Stk. Hengstenberg KNAX Gewürzgurken (0,95 EUR)

bei REAL 25 Stk.Knorr Schlemmer-Saucen 250ml, divS. (0,69 EUR)

bei Edeka/Treff 100 Stk. Hawesta Heringsfilets 200g, divS. (1,11 EUR)

bei Edeka/Treff 100 Stk. Erasco Fertiggericht 800g, divS. (kein Reistopf) (1
49 EUR)

bei Treff3000 200 Stk. Maggi fix & frisch, div Sorten (0,49 EUR)

bei NETTO 100 Stk. Maggi Ravioli 800g, divS. (1,29 EUR)

2.) MITTEL

bei NETTO 50 Stk. Maggi Guten Appetit Suppe, divS. (0,49 EUR)

bei Edeka/Treff 50 Stk. Ritter Sport Schoko, 100g, divS. (0,69 EUR)

3.) WENIGER

bei REAL 10 Stk. Funny-Frisch oder Ohio Chips 175g, (1,29 EUR)

bei EDEKA 5 Stk. Haribo Goldbären 1kg Packung (3,49 EUR)

bei Edeka-ECenter/Marktkauf 25 Stk. Kühne Senf mittelscharf 240ml Tube (+20%
Inhalt) (0,99 EUR)

bei Edeka-ECenter/Marktkauf 20 Stk. Leimer Backerbsen 200g (+10% Inhalt) (0
88 EUR)

**Comment by speednic** [comment]
ok, dann nehmen wir gesamt nur 100 Maggi+Erasco, weil karin will ja schon alleine 36 Ravioli von Maggi

**Comment by speednic** [comment]
hatte ich befürchtet, Katja meint das ist ihr zuviel Menge und Aufwand, weil klar muss halt ein paar mal hinfahren wegen "haushaltsüblichen" Mengen ...

also da brauchen wir eine andere Lösung die zeitlich flexibler ist ...

**Comment by speednic** [comment]
aktuell diese Woche ... 

EDEKA       Haribo 200g          0,66
EDEKA       Maggi Fix & Frisch       0,49
EDEKA       Kühne GGurken/Ung.Gurk/MoskG    0,99
EDEKA       Milka 100g (+15%)        0,79

EDEKA-ECenter   Hawesta Hering 200g      1,11
EDEKA-ECenter   Kühne Gurken 670g       0,99
EDEKA-ECenter   Maggi fix & Frisch       0,49
EDEKA-ECenter   G&Günstig Heringsfilet 200g     0,79
EDEKA-ECenter   G&Günstig Spritz-Gebäck 500g   1,09
EDEKA-ECenter   Haribo 200g          0,66
EDEKA-ECenter   Funny-Frisch Chips/Flips     1,29
EDEKA-ECenter   Milka 100g (+155)        0,79

REAL        Nutella 450g (+Spiel bei 2Gl.)   1,79
REAL        Erasco Eintopf 800g      1,49 (ab 5 Dosen)
REAL        Knorr SalatKrönung 5er      0,75 (ab 3 Pkg)
REAL        Erdnüsse 200g (3 Stk.)      3,00 (3er Pack)
REAL        Ritter Sport 100g        0,59
REAL        Milka 200/300g Tafel         2,29
REAL        Malibu 0,7L         10,99

ALDI-SÜD   -

NETTO       Beste Ernte Gewürzgürken 850ml     0,79
NETTO       Erasco Eintopf 800g      1,49
NETTO       Hawesta Heringsfilets 200g   1,11
NETTO       Katjes 200g          0,49
NETTO       Ritter Sport 100g        0,69

**Comment by speednic** [comment]
OHNE WORTE !!!!!!! Originalmessage : 

Gestern hatte ich bei EDEKA mein Aha Erlebnis. Nach dem Einkauf bei Netto 
bin ich noch zum EDEKA in Lindau gefahren (der war mir nicht bewußt). Hab 
dort die 200 Stck. Maggi Fix & Frisch in 5 Kartons a 40 Stck. (gemischt) 
reingepackt und die 50 Tafeln Milkaschokolade schließlich auf das Band bei 
der Kasse gestellt. Der Kassierer hat dann gemeint, das wären keine 
haushaltsüblichen Mengen. Worauf ich ihn dann fragte, was haushaltsübliche 
Mengen sind. Er darauf, 3 bis 4 Tüten und 3 bis 4 Schokolade. Ich fragte 
ihn nochmal und er wiederholte dasselbe. Ich darauf, wegen 3 bis 4 Tüten / 
Tafeln gehe ich nicht einkaufen. Hab die Ware auf dem Band liegen gelassen 
und bin gegangen. Der Knackpunkt war, daß ich genau zum Kassenschluß (20 
Uhr) an der Kasse stand und die faule Sau keine Lust mehr zum Zählen 
hatte. Er hat sich sicherlich trotzdem hinterher gefreut, da er alles 
wieder ins Regal räumen durfte. Die Kartons waren von Sorten gemischt. 
Jetzt kenne ich auch den Begriff der haushaltsüblichen Menge. Hatte bisher 
noch nicht den Konflikt, da ich noch nie soviel eingekauft habe 
(vielleicht mal 10 Schokolade, wenn im Angebot). Ich frag' mich nur, ob es 
bei der deutschen Gründlichkeit hierfür auch eine DIN oder ISO Norm gibt! 
3 bis 4 Tüten / Tafeln ist ja wohl ein Witz. Wenn ich beim Lidl stehe, 
sehe ich oftmals Leute, die Mengen einkaufen, wo man sich frägt, ob das 
für ein Hotel oder Gaststätte ist. Aber, da gab's niemals Probleme. Ich 
vermute, mein Timing war halt schlecht.

**Comment by speednic** [comment]
NETTO :  50 Stk. Knorr Salatkrönung, div. sorten ... 0,79 Euro
Gekauft. 3 Kartons a 18 Stck. (54 Stck.) gekauft. Je nach Sorte Verfall zwischen 02 und 06/2016.
lt. kassenbon : 5x SKR Paprika, 17x SKR Italienisch , 31x SKR Gartenkräuter, 1x SkR 5+1 sort.VE

NETTO :  50 Stk. Ritter Sport Schoko, 100g, div. sorten ... 0,69 Euro
Gekauft.
lt. kassenbon : 37x sort., 13x Rum/Marzipan

gesamt 77,85 Euro

**Comment by speednic** [comment]
neuer einkauf von gestern bei KAUFLAND :

11x Appel Heringsfilets a 1,11 Euro
50x Knorr Fix (10 sorten a 5) a 0,44 Euro

gesamt 34,21 Euro

**Comment by speednic** [comment]
KAUFLAND :

30x APPEL Heringsfilets (div. sorten) ... 33,30 EURO
25x Milka Alpenmilch (div. sorten) ... 19,75 EURO
  6x Backerbsen ... 8,34 EURO
50x Maggi Fix ... 24,50 EURO

das ist dann alles was er shoppen kann aktuell ... weil er muss jetzt Jahresabschluss machen für die Chinesen :D

**Comment by Holgerreetz** [comment]
wie schon gesagt,  jedes teil bringt gewinn 

-------Originalmeldung-------

Von: speednic

Datum: 01/26/15 15:04:38

An: SPEEDNIC-SRL/pyimport

Cc: Holgerreetz

Betreff: Re: [pyimport] Supermarkt DE - aktuell via Eddi (#36)

KAUFLAND :

30x APPEL Heringsfilets (div. sorten) ... 33,30 EURO

25x Milka Alpenmilch (div. sorten) ... 19,75 EURO

6x Backerbsen ... 8,34 EURO

50x Maggi Fix ... 24,50 EURO

das ist dann alles was er shoppen kann aktuell ... weil er muss jetzt
Jahresabschluss machen für die Chinesen :D
