### ISSUE TITLE
Helmut - Ware Österreich

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#37]
hab mal senf und ein paar andere sachen in auftrag gegeben :) 

schlenz hab ich per whatsapp contaktiert, mal schaun was kommt ...

notfalls muss das zeug nach DE rauf, da hab ich dann wenigstens ausrede für peter _hehe_ :)

**Comment by speednic** [comment]
also ware geht via SCHLENZ in AT weg ... geplant derzeit ggf. sogar 1cbm (warte noch auf die Masse von den Sachen meiner Mutter) weil effektiv billiger, dann auch fürs BIER :)

**Comment by speednic** [comment]
aktuell gekauft für mich :  

20x Würstelsenf (10 süs, 10 mittel) a 0,66
  5x manner neapolitaner a 1,49
  5x kümmel ganz 140g a 0,99
10x Brathuhngewürz 140g a 0,99
10x paprika edelsüß 140g a 0,99
10x pfeffer schwarz gemaheln 140g a 1,29

**Comment by speednic** [comment]
gekauft 
10 Stk. Erdnüsse 500g, je 1,49 Euro

**Comment by speednic** [comment]
gewürzgläser kommen noch 20 stk. mit, u.a. cayene, usw., und aktuell 10 suppen von knorr

**Comment by Holgerreetz** [comment]
Auch kleinvieh macht mist, jedes stück bringt guaranis

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 25.01.2015  17:18  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Betreff: Re: [pyimport] Helmut - Ware Österreich (#37)

gewürzgläser kommen noch 20 stk. mit, u.a. cayene, usw., und aktuell 10 suppen von knorr

---

**Comment by speednic** [comment]
einkaufswagen hat man eh gesehen ... es lebe die family :+1:
