### ISSUE TITLE
Gewürze

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#38]
via amazon - vom-Achterhof (DE)
9,95 Euro ... 1kg Piment ganz
9,95 Euro ... 1kg Wacholderbeeren ganz
9,95 Euro ... 1kg Zimtstangen Cassia
3,49 Euro ... 1kg Senfsaat gelb
7,95 Euro ... 1kg Ingwer gemahlen
9,90 Euro ... 1kg Thymian gerebelt (a 500g)

gesamt 64,63 Euro (Versandkostenfrei lustigerweise obwohl versand dabei stand)
lieferung 27-30.01.

**Comment by speednic** [comment]
via amazon - PRIME Versand
9,95 Euro ... 1kg Basilikum gerebelt
9,95 Euro ... 1kg Paprika Rosenscharf
16,41 Euro ... 1kg Fuchs Lorbeerblätter (2x 500g) ... sind billiger als die vom achterhof

gesamt 59,40 Euro (versandkotenfrei)
inkl. 6 stk. limburg champignons :) dürften noch 1 pack auf lager haben

**Comment by Holgerreetz** [comment]
Ja das nehmen wir

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 25.01.2015  18:49  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Betreff: Re: [pyimport] Gewürze (#38)

via amazon - PRIME Versand
9,95 Euro ... 1kg Basilikum gerebelt
9,95 Euro ... 1kg Paprika Rosenscharf
16,41 Euro ... 1kg Fuchs Lorbeerblätter (2x 500g) ... sind billiger als die vom achterhof

gesamt 59,40 Euro (versandkotenfrei)
inkl. 6 stk. limburg champignons :) dürften noch 1 pack auf lager haben

---

**Comment by Holgerreetz** [comment]
Bitte Ohne  ingwer

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 25.01.2015  18:28  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Betreff: [pyimport] Gewürze (#38)

via amazon - vom-Achterhof (DE)
9,95 Euro ... 1kg Piment ganz
9,95 Euro ... 1kg Wacholderbeeren ganz
9,95 Euro ... 1kg Zimtstangen Cassia
3,49 Euro ... 1kg Senfsaat gelb
7,95 Euro ... 1kg Ingwer gemahlen
9,90 Euro ... 1kg Thymian gerebelt (a 500g)

---

Reply to this email directly or view it on GitHub:
https://github.com/SPEEDNIC-SRL/pyimport/issues/38

**Comment by speednic** [comment]
ist schon alles bestellt :)

**Comment by Holgerreetz** [comment]
Ok

Saludos

Holger Reetz

Atlantida / Uruguay

-------- Ursprüngliche Nachricht --------
Von: speednic notifications@github.com
Datum: 25.01.2015  18:52  (GMT-03:00)
An: SPEEDNIC-SRL/pyimport pyimport@noreply.github.com
Cc: Holgerreetz reetz_4@hotmail.com
Betreff: Re: [pyimport] Gewürze (#38)

ist schon alles bestellt :)

---

**Comment by speednic** [comment]
Majoran vergessen :(
