### ISSUE TITLE
Zusatzeinkäufe Amazon/etc.

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#39]
9,54 EUR ... 1x (6) Bücklingsfilets 190g
10,32 EUR ... 3x (8) Sprotten in Tomatensauce 240g
  8,94 EUR ... 2x (6) Sprotten in Öl 160g
## 11,12 EUR ... 4x (8) Reisstrohpilze 425g

102,86 EUR Gesamt inkl. Versandkosten

**Comment by Holgerreetz** [comment]
ok  die nehmen wir noch 

-------Originalmeldung-------

Von: speednic

Datum: 01/26/15 14:47:19

An: SPEEDNIC-SRL/pyimport

Betreff: [pyimport] Zusatzeinkäufe Amazon/etc. (#39)

9,54 EUR ... 1x (6) Bücklingsfilets 190g

10,32 EUR ... 3x (8) Sprotten in Tomatensauce 240g

8,94 EUR ... 2x (6) Sprotten in Öl 160g

11,12 EUR ... 4x (8) Reisstrohpilze 425g

102,86 EUR Gesamt inkl. Versandkosten

**Comment by speednic** [comment]
wie gesagt noch ein paar kleinigkeiten ... ist dann alles in der liste vermerkt ... ggf. die Bohnen storniere ich morgen weil die sind noch immer nicht im Versand obwohl seit tagen steht "wird vorbereitet"
