### ISSUE TITLE
Bestellung Karin / Melgarejo

### ISSUE THREAD

**Issue by speednic** [SPEEDNIC-SRL/pyimport#4]
Bestellung Karin

60 Kirschen im Glas (nicht von Aro)
12 Preiselbeeren
36 Ravioli mild-scharf
24 Brathering
50 Heringsfilet tomate,paprika,etc.
24 Champignons  mittlere Dosen
36 Nutella 400g
36 Milde Pepperoni im Glas
24 Artischockenherzen Dose (edeka od.beste ernte)
30 paq. Salatkrönung
50 Vanillezucker
30 Puddingpulver vanille
20 Puddingpulver schoko
25 Gelierzucker 500g
24 Senf süss
50 Senf mittelscharf
12 Senf Bautzener 1K-Eimer

1 Ketchup 10 Kilo-Eimer
1 Gewürzketchup 10 Kilo-Eimer
1 Mittelscharfer Senf 10 Kilo-Eimer

6 L Jägermeister

Die unterstrichenen Sachen wären mir am wichtigsten.
Wäre es möglich,dass ich einen 20-25 Kilo Sack Himalayasalz bestelle und zu einer von
Dir genannten Adresse schicken lasse und du mir dann einfach die Fracht berechnest?
Wenn ja,dann würde ich den gleich die Tage bestellen,damit er noch rechtzeitig kommt.
Gruss Karin

**Comment by Holgerreetz** [comment]
Hinzu kommen 
100 Haribo gemischt, vorwiegend Lakritze
 50 Pumpernickel
100 maggi sossen und Fixprodukte
 30 Teebaumöl
36 Gw.Gurken Knax 
 50 m Heftpflaster

**Comment by speednic** [comment]
zusatzbestellung Karin :

50 Packungen Pads von Aldi/Netto/Lido, ca. 1,70 Euro pro 20 Stk., keinen entkofeinierten, classic oder so heissen die meistens (sagt sie)

**Comment by Holgerreetz** [comment]
Such ich na hher raus

Saludos

Holger Reetz

Atlantida  Uruguay

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: speednic <notifications@github.com> </div><div>Datum:19.01.2015  15:42  (GMT-04:00) </div><div>An: SPEEDNIC-SRL/pyimport <pyimport@noreply.github.com> </div><div>Cc: Holgerreetz <reetz_4@hotmail.com> </div><div>Betreff: Re: [pyimport] Bestellung Karin / Melgarejo (#4) </div><div>
</div>

zusatzbestellung Karin :

50 Packungen Pads von Aldi/Netto/Lido, ca. 1,70 Euro pro 20 Stk., keinen entkofeinierten, classic oder so heissen die meistens (sagt sie)

---

**Comment by speednic** [comment]
das käme vom preis her hin ... sind halt nur 16 stk. dafür marke ... http://www.mytime.de/product.php?product_id=9da933d0c33fe80422d643e6d6bd43b4&search_query=pads

gäbe um 1,69 auch 20 stk. von JedenTag bei mytime ...

**Comment by speednic** [comment]
OFFEN ... Bestellung Karin

36 Ravioli mild-scharf
100 maggi sossen und Fixprodukte

da sollten wir noch schaun was wir da ggf. bekommen, rest ist alles bestellt ;)

**Comment by speednic** [comment]
also bis auf RAVIOLI alles vorhanden ...
